# .github/workflows/scheduled-builds.yml
name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '55 11 * * *'
  push:
    branches:
      - master

jobs:
  message:
    environment: PROD
    name: SendMessage
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run python script
        run: |
          pip install requests python-dotenv && python ./send_message.py